-- ================================================================
-- Redesign: Link-Based Kasir Invitation System
-- Date: 2026-03-15
--
-- Changes:
--   1. SCHEMA: invitations table — add token UUID, email nullable
--   2. RPC: get_invite_preview(token) — PUBLIC (anon + authenticated)
--   3. RPC: create_invite_link(email, role) — replaces create_invitation
--   4. RPC: accept_invite_by_token(token) — replaces accept_invitation
--
-- Backward Compat: create_invitation, accept_invitation, revoke_invitation,
--   remove_kasir are all untouched.
-- ================================================================


-- ─────────────────────────────────────────────────────────────
-- 1. Schema changes: invitations table
-- ─────────────────────────────────────────────────────────────

-- 1a. Add token column (UUID) — used in shareable URL
ALTER TABLE public.invitations
  ADD COLUMN IF NOT EXISTS token UUID DEFAULT gen_random_uuid();

-- Populate token for existing rows
UPDATE public.invitations SET token = gen_random_uuid() WHERE token IS NULL;

-- Make non-nullable and unique after populating
ALTER TABLE public.invitations ALTER COLUMN token SET NOT NULL;
ALTER TABLE public.invitations ADD CONSTRAINT invitations_token_unique UNIQUE (token);

-- 1b. Make email nullable (open invite links, no email restriction)
ALTER TABLE public.invitations ALTER COLUMN email DROP NOT NULL;

-- 1c. Fast index for token lookup
CREATE UNIQUE INDEX IF NOT EXISTS idx_invitations_token
  ON public.invitations (token);


-- ─────────────────────────────────────────────────────────────
-- 2. RPC: get_invite_preview
--    PUBLIC — callable by anon and authenticated roles.
--    Kasir can preview pharmacy info BEFORE creating an account.
--    Email is obfuscated (e.g. "ku***@gmail.com") for privacy.
-- ─────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.get_invite_preview(p_token UUID)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_rec RECORD;
BEGIN
  SELECT
    i.expires_at,
    i.used_at,
    i.email,
    u.pharmacy_name,
    u.full_name  AS owner_name,
    u.logo_url
  INTO v_rec
  FROM  public.invitations i
  JOIN  public.users       u ON u.id = i.owner_id
  WHERE i.token = p_token;

  IF NOT FOUND THEN
    RETURN json_build_object('error', 'not_found');
  END IF;

  IF v_rec.expires_at < NOW() THEN
    RETURN json_build_object('error', 'expired');
  END IF;

  IF v_rec.used_at IS NOT NULL THEN
    RETURN json_build_object('error', 'already_used');
  END IF;

  RETURN json_build_object(
    'pharmacy_name', v_rec.pharmacy_name,
    'owner_name',    v_rec.owner_name,
    'logo_url',      v_rec.logo_url,
    -- Obfuscate email: show "ku***@gmail.com" so kasir recognises it's theirs
    -- without exposing full address to random visitors
    'email', CASE
      WHEN v_rec.email IS NULL THEN NULL
      ELSE LEFT(v_rec.email, 2)
           || '***@'
           || SPLIT_PART(v_rec.email, '@', 2)
    END,
    'expires_at', v_rec.expires_at
  );
END;
$$;

-- Grant to both anon (public preview before login)
-- and authenticated (re-fetch after login to know pharmacy name)
REVOKE EXECUTE ON FUNCTION public.get_invite_preview(UUID) FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION public.get_invite_preview(UUID) TO anon;
GRANT  EXECUTE ON FUNCTION public.get_invite_preview(UUID) TO authenticated;


-- ─────────────────────────────────────────────────────────────
-- 3. RPC: create_invite_link
--    Called by Settings.tsx instead of create_invitation.
--    Returns { token, code } — token for the URL link,
--    code (8-char) kept as manual fallback.
--    email can be NULL for open links (any kasir can join).
-- ─────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.create_invite_link(
  p_email TEXT    DEFAULT NULL,
  p_role  TEXT    DEFAULT 'cashier'
)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_owner_id UUID := auth.uid();
  v_code     TEXT;
  v_token    UUID;
  v_id       UUID;
BEGIN
  IF v_owner_id IS NULL THEN
    RAISE EXCEPTION 'Unauthorized';
  END IF;

  -- Invalidate any existing pending invite for this email (if email supplied)
  IF p_email IS NOT NULL THEN
    UPDATE public.invitations
       SET expires_at = NOW() - INTERVAL '1 second'
     WHERE owner_id = v_owner_id
       AND email    = LOWER(TRIM(p_email))
       AND used_at  IS NULL;
  END IF;

  -- Generate unique 8-char code (kept for SMS/verbal fallback)
  LOOP
    v_code := UPPER(SUBSTRING(MD5(RANDOM()::TEXT || NOW()::TEXT) FROM 1 FOR 8));
    EXIT WHEN NOT EXISTS (SELECT 1 FROM public.invitations WHERE code = v_code);
  END LOOP;

  -- token is auto-generated by DEFAULT gen_random_uuid()
  INSERT INTO public.invitations (owner_id, email, role, code)
  VALUES (
    v_owner_id,
    CASE WHEN p_email IS NOT NULL THEN LOWER(TRIM(p_email)) ELSE NULL END,
    p_role,
    v_code
  )
  RETURNING id, token INTO v_id, v_token;

  RETURN json_build_object(
    'id',    v_id,
    'token', v_token,
    'code',  v_code
  );
END;
$$;

REVOKE EXECUTE ON FUNCTION public.create_invite_link(TEXT, TEXT) FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION public.create_invite_link(TEXT, TEXT) TO authenticated;


-- ─────────────────────────────────────────────────────────────
-- 4. RPC: accept_invite_by_token
--    Called by /join page after user authenticates.
--    Uses SELECT FOR UPDATE to prevent double-accept race condition.
--    Upserts profile row if brand-new signup has no profile yet.
-- ─────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.accept_invite_by_token(p_token UUID)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_inv        public.invitations%ROWTYPE;
  v_user_id    UUID;
  v_user_email TEXT;
BEGIN
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Sesi tidak ditemukan. Silakan login terlebih dahulu.';
  END IF;

  -- Lock the row to prevent concurrent double-accepts
  SELECT * INTO v_inv
    FROM public.invitations
   WHERE token = p_token
   FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Undangan tidak ditemukan';
  END IF;

  IF v_inv.expires_at < NOW() THEN
    RAISE EXCEPTION 'Undangan sudah kadaluarsa';
  END IF;

  IF v_inv.used_at IS NOT NULL THEN
    RAISE EXCEPTION 'Undangan ini sudah pernah digunakan';
  END IF;

  -- Email check: only enforce if owner specified an email for this invite
  SELECT email INTO v_user_email FROM auth.users WHERE id = v_user_id;

  IF v_inv.email IS NOT NULL AND LOWER(v_user_email) != LOWER(v_inv.email) THEN
    RAISE EXCEPTION 'Email akun Anda tidak sesuai dengan undangan ini (undangan untuk: %)',
      LEFT(v_inv.email, 2) || '***@' || SPLIT_PART(v_inv.email, '@', 2);
  END IF;

  -- Ensure profile row exists (handles brand-new signups with no row yet)
  INSERT INTO public.users (id, full_name, pharmacy_name, pharmacy_address, role)
  VALUES (
    v_user_id,
    SPLIT_PART(COALESCE(v_user_email, 'kasir'), '@', 1),
    'Kasir',
    '-',
    'cashier'
  )
  ON CONFLICT (id) DO NOTHING;

  -- Link kasir to owner, set role to cashier
  UPDATE public.users
     SET pharmacy_owner_id = v_inv.owner_id,
         role              = 'cashier'
   WHERE id = v_user_id;

  -- Mark invite as consumed
  UPDATE public.invitations
     SET used_at = NOW(),
         used_by = v_user_id
   WHERE id = v_inv.id;

  RETURN json_build_object(
    'success',  true,
    'owner_id', v_inv.owner_id
  );
END;
$$;

REVOKE EXECUTE ON FUNCTION public.accept_invite_by_token(UUID) FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION public.accept_invite_by_token(UUID) TO authenticated;
